language: node_js
node_js:
  - 6.10.3

before_script:
  - npm run build

jobs:
  include:
    - stage: npm release
      node_js: "6.10.3"
      script: echo "Deploying to npm ..."
      deploy:
        api_key: $NPM_API_KEY
        tag: beta
        email: vladimirmorulus@gamil.com
        provider: npm
        skip_cleanup: true
        on:
          branch: beta
